### ISSUE TITLE
Code first

### ISSUE THREAD

**Issue by dentia** [Team-Tyche/Just-DIY#1]
Category (enum) - Hardware/Software

Project
        int Id [PK]
        int UserId
        int CategoryId
        string Name
        date CreatedOn
        text Content
        string[not required] url
        int Votes

Votes
        int UserId [PK]
        int ProjectId [PK]
        int/byte or whatever Value

Favorites
        int UserId [PK]
        int ProjectId [PK]

**Comment by ahansb** [comment]
Done User is not implemented
